---
title: <center><h1> 5104 Project</h1></center><br />
author: <center>Yiu Chung WONG 1155017920</center>
date: <center>`r format(Sys.time(), '%d %B, %Y')`</center>
output:
  html_document:
    keep_md: yes
  pdf_document: default
  word_document: default
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
set.seed(5104)
```

## Download Data

```{r Download data}
url <- "http://archive.ics.uci.edu/ml/machine-learning-databases/00373/drug_consumption.data"
drug.use <- read.csv(url, sep = ",", header = FALSE)
column.names <- c("ID", "Age", "Gender", "Education", "Country", "Ethnicity", "Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsive", "SS", "Alcohol", "Amphet", "Amyl", "Benzos", "Caff", "Cannabis", "Choc", "Coke", "Crack", "Ecstasy", "Heroin", "Ketamine", "Legalh", "LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA")
colnames(drug.use) <- column.names
head(drug.use)
```

## Clean Data

* Remove `ID`
* Give labels to column 2 - 6

```{r pressure, echo=FALSE}
drug.clean <- drug.use %>%
                as_tibble %>%
                mutate_at(vars(Age:Ethnicity), funs(as.factor)) %>%
                mutate(Age = factor(Age, labels = c("18_24", "25_34", "35_44", "45_54",                       "55_64", "65_"))) %>%
                mutate(Gender = factor(Gender, labels = c("Male", "Female"))) %>%
                mutate(Education = factor(Education, labels = c("Under16", "At16", "At17",                    "At18", "SomeCollege","ProfessionalCert", "Bachelors", "Masters",                             "Doctorate"))) %>%
                mutate(Country = factor(Country, labels = c("USA", "NewZealand", "Other",                     "Australia", "Ireland","Canada","UK"))) %>%
                mutate(Ethnicity = factor(Ethnicity, labels = c("Black", "Asian", "White",                    "WhiteBlack", "Other", "WhiteAsian", "BlackAsian"))) %>%
                select(-ID)

head(drug.clean)
```


